name: Node Continuous Integration

on:
  push:
    branches-ignore:
      - Production
      - Preview
  pull_request:
    branches-ignore:
      - Production
      - Preview

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Prettier formatting
        run: pnpm format

      - name: Froze yarn.lock file
        run: pnpm install --frozen-lockfile

      - name: Check format
        run: pnpm run format:check

      - name: Build packages
        run: pnpm build
