version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamify-docker
    ports:
      - "4001:3000"
    volumes:
      - .:/app
      - /app/node_modules
