name: Feature request
description: Suggest an idea to help us improve 
title: "[Feature request]: "
labels: ["Feature request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this feature request!
  - type: markdown
    attributes:
      value: ---
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem? Please describe this problem.
      description: A clear and concise description of what the problem is.
      placeholder: Write your text here.
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you would like.
      description: A clear and concise description of what you want to happen.
      placeholder: Write your text here.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: How do you solve this problem at the moment?
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Write your text here.
    validations:
      required: true
  - type: dropdown
    id: alternatives-existing
    attributes:
      label: Do you use or know other tools which serves your needs?
      description: What version of our software are you running?
      options:
        - 'Yes'
        - 'No'
      default: 0
    validations:
      required: true
  - type: textarea
    id: alternative-names
    attributes:
      label: If yes, please list them.
      description: URL to the website would be perfect!
      placeholder: Write your text here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else left you want to tell us?
      description: Add any other context or screenshots about the feature request here.
      placeholder: Write your text here.
    validations:
      required: false
