name: Update licenses
on:
  push:
    branches:
      - main
    paths:
      - apps
      - packages
jobs:
  create-licenses-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update licenses
        # In the long run, we should decide which of these tools we want to use. For now, save output of all to
        # be able to compare.
        run: |
          pnpm install
          npx license-checker-rseidelsohn --excludePrivatePackages --json | sed -E 's/"(path|licenseFile)": "(.*)\/streamify.com/"\1": "streamify.com/g' > licensing/licenses.json
          pnpm licenses list | sed -e 's/└─ workspace-aggregator-.*\@/streamify-workspace@/g' | sed -e 's/Done in .*\.//g' > licensing/yarn-licenses.json
          pnpm licenses generate-disclaimer | sed -e 's/WORKSPACE AGGREGATOR .* PRODUCT/STREAMIFY PRODUCT/g' > licensing/yarn-disclaimer.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Licenses
          title: Update Licenses
          body: New licenses detected in dependencies, updated licenses.json
          branch: update-licenses
